CREATE TABLE USERS(
    ID INT64 NOT NULL,
    NAME STRING(MAX) NOT NULL,
    EMAIL STRING(MAX) NOT NULL,   
) PRIMARY KEY (ID);


INSERT INTO USERS(NAME, EMAIL, ID ) VALUES("John Doe","JOHN.DOE@GMAIL.COM", 1);
INSERT INTO USERS(id, name, email) VALUES(2, "Nikhil Ajabe","nikiik@mail.com");

DROP TABLE USERS;