DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS(
    ID INT64 NOT NULL,
    NAME STRING(MAX) NOT NULL,
    EMAIL STRING(MAX) NOT NULL
) PRIMARY KEY (NAME, ID);

INSERT INTO USERS(ID, NAME, EMAIL) VALUES(1, 'Alice Smith', 'alice@example.com');
INSERT INTO USERS(ID, NAME, EMAIL) VALUES(2, 'Bob Jones', 'bob@example.com');
INSERT INTO USERS(ID, NAME, EMAIL) VALUES(3, 'Charlie Brown', 'charlie@example.com');


DROP TABLE USERS;